### ISSUE TITLE
error: 'pi' was not declared in this scope

### ISSUE THREAD

**Issue by gmatteo** [piti-diablotin/abiout#4]
Compiler: gcc version 7.3.0 (crosstool-NG 1.23.0.452-d158)

make[2]: Entering directory '$SRC_DIR/src/window'
  CXX      window.lo
window.cpp: In member function 'virtual void Window::loopStep()':
window.cpp:464:86: error: 'pi' was not declared in this scope
     this->lookAt(paral_proj? totalfactor : totalfactor/tan(_optionf["perspective"] * pi/(2.*180.)),0,0,0);
                                                                                      ^~
window.cpp:464:86: note: suggested alternative:
In file included from ../../include/io/configparser.hxx:35:0,
                 from ../../include/io/configparser.hpp:163,
                 from ../../include/window/window.hpp:44,
                 from window.cpp:27:
../../include/base/phys.hpp:54:16: note:   'phys::pi'
   const double pi = 3.1415926535897932384626433832795; ///< pi ...
                ^~
make[2]: *** [Makefile:401: window.lo] Error 1
make[2]: Leaving directory '$SRC_DIR/src/window'
make[1]: *** [Makefile:488: all-recursive] Error 1
make[1]: Leaving directory '$SRC_DIR'
make: *** [Makefile:399: all] Error 2

**Comment by piti-diablotin** [comment]
Thanks for the report.
Fixed in eb24ea46dcb90590739d14d5fdd26447ddbe151a
